INSERT INTO exercises (name, image_url, level, muscle_groups, reps, description) values ('The Plank','https://www.verywellfit.com/thmb/oznxN3FOnjQTkDrSQs14JAacQD0=/768x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-598308041-5707ef713df78c7d9ea4f5ee.jpg','Intermediate','Abdominals and glutes','2 x hold for 1 minute with 20s break','In the pushup position, but put your forearms on the ground instead of your hands. Squeeze glutes and tighten your abdominals. Keeping a neutral neck and spine, create a straight line from head to toes. Hold that position');

INSERT INTO exercises (name, image_url, level, muscle_groups, reps, description) values ('Teaser','http://rescu.com.au/wp-content/uploads/2015/06/KX-Pilates-Boat-Pose-21.jpg','Advanced','Abdominals, Hip flexors','2 sets of 12','Laying on your back on a mat, legs straight along the floor and arms wide to the side on the chest. Inhale to prepare and squeeze abdominals, then exhale as you lift the head, chest, arms, feet and knees, and sit up into a V pose position, balancing on your bottom with your arms stretched forward in front. Add light dumbells to advance');


INSERT INTO exercises (name, image_url, level, muscle_groups, reps, description) values ('Side-plank','https://static1.squarespace.com/static/534d96c2e4b06f18b87bf433/t/580e9f2303596ec8949cb156/1477353270319/Man+doing+planks.jpg','Intermediate','Obliques, Abdominals','2 x hold for 1 minute','Place forearm on mat under shoulder perpendicular to body. Place upper leg directly on top of lower leg and straighten knees and hips. Raise body upward by straightening waist so body is straight. Hold position.');



INSERT INTO exercises (name, image_url, level, muscle_groups, reps, description) values ('Bridge with leg raises','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQj8oUFwVdE7DFJKQq__MunROdo6PPvCRLuuog5REm-5W8v0sDlyQ','Beginner','Glutes, Hamstrings, Adductors, Hipflexors, Obliques','3 sets of 12, alternating legs','Lie on your back with knees bent and feet flat on the floor. Keep your arms at your side with your palms down. Lift your hips off the ground until your knees, hips and shoulders form a straight line. Hold your bridged position for a couple of seconds, to progress, raise one foot (toes pointing to the ceiling - see image) and return. Alternating each leg. Try keep hips level in the air as you shift legs.');